# TODO: Remove this file once new version of cnpg cluster chart with managed roles support is released
{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "big-agi.fullname" . }}-postgres
  labels:
    {{- include "big-agi.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.cluster.instances }}
  storage: {{ .Values.postgres.cluster.storage | toYaml | nindent 4 }}
  enableSuperuserAccess: {{ .Values.postgres.cluster.enableSuperuserAccess }}
  {{- with .Values.postgres.cluster.superuserSecret }}
  superuserSecret:
    name: {{ . }}
  {{ end }}

  managed:
    roles:
      - name: {{ .Values.postgres.username }}  # this should match the username in secret
        ensure: present
        login: true
        superuser: true
        createrole: true
        passwordSecret:
          name: {{ include "big-agi.fullname" . }}-pgsecret
        inRoles:
          - pg_read_all_data
          - pg_write_all_data
{{- end }}
